spring:
  profiles:
    active: dev
---
#开发环境
server:
  port: 8080
  #是否开启压缩
  compression:
    enabled: true
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://127.0.0.1/okc?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #阿里druid数据库连接池配置
    druid:
      initial-size: 5
      min-idle: 2
      max-active: 30
      test-on-borrow: true
      stat-view-servlet.allow: true
      min-evictable-idle-time-millis: 100000
      filters: config
      connectionProperties: config.decrypt=true;config.decrypt.key=${publickey}

  #文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: "20MB"
      max-request-size: "100MB"
      resolve-lazily: true

mybatis:
  type-aliases-package: com.okc.common.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.common.MySqlMapper
#分页
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
#记录sql
logging:
  level:
    com:
      okc:
        common:
          mapper: trace

fdfs:
  absolute-address: http://192.168.18.253:8888/
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.18.253:22122
  pool:
    #从池中借出的对象的最大数目
    max-total: 153
    max-wait-millis: 102
    jmx-name-base: 1
    jmx-name-prefix: 1
    jmx-enabled: false

ignore:
  urls:
    - /
    - /test/**
    - /fdfs/**
    - /wechat/**
    - /error
    - /swagger-ui.html
    - /swagger-resources/**
    - /v2/api-docs
    - /common/**
    - /index/**
    - /home/**
---
#生产环境
server:
  port: 8080
  #是否开启压缩
  compression:
    enabled: true
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://127.0.0.1/okc?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #阿里druid数据库连接池配置
    druid:
      initial-size: 5
      min-idle: 2
      max-active: 30
      test-on-borrow: true
      stat-view-servlet.allow: true
      min-evictable-idle-time-millis: 100000
      filters: config
      connectionProperties: config.decrypt=true;config.decrypt.key=${publickey}

  #文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: "20MB"
      max-request-size: "100MB"
      resolve-lazily: true

mybatis:
  type-aliases-package: com.okc.common.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.common.MySqlMapper
#分页
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
#记录sql
logging:
  level:
    com:
      okc:
        common:
          mapper: trace

fdfs:
  absolute-address: http://192.168.18.253:8888/
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.18.253:22122
  pool:
    #从池中借出的对象的最大数目
    max-total: 153
    max-wait-millis: 102
    jmx-name-base: 1
    jmx-name-prefix: 1
    jmx-enabled: false

ignore:
  urls:
    - /
    - /test/**
    - /fdfs/**
    - /wechat/**
    - /error
    - /swagger-ui.html
    - /swagger-resources/**
    - /v2/api-docs
    - /common/**
    - /index/**
    - /home/**

